# Generated by Django 5.1.7 on 2025-03-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_alter_appointment_customer_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="job",
        ),
        migrations.AddField(
            model_name="appointment",
            name="jobs",
            field=models.ManyToManyField(blank=True, to="scheduler.job"),
        ),
    ]
