# Generated by Django 5.1.7 on 2025-03-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_remove_appointment_job_appointment_jobs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="custom_job",
            new_name="custom_job_name",
        ),
    ]
